[COH-17363] Enhance/control renoir caches
CoherentLabs/devtools-frontend-fork pull request #8
Opened 2023-03-24 16:58 UTC by palikar

2023-04-11 12:07 UTC, alien1976 requested changes
* Maybe add max/min value to the input fields because it assets if > 3gb
![image](https://user-images.githubusercontent.com/29014573/231157398-c72094d8-fbe4-4399-b8be-9dd3e2596434.png)
* Used images section is broken (the green color highlights the locations where it should be shown)
![image](https://user-images.githubusercontent.com/29014573/231157622-525de310-040c-4718-b8cc-bdfa0df1e335.png)
* When you resize the inspector the input fields are overflowing and are not responsive. Either fix this or create a task in the FE board so we can fix it when we have time.
![image](https://user-images.githubusercontent.com/29014573/231157835-e1d28a94-e379-4eb2-928c-7f27d5951020.png)

2023-04-11 12:07 UTC, alien1976 commented on front_end/core/sdk/CohtmlDebugModel.ts
> +  setRenoirCacheState(stateToSet: Protocol.CohtmlDebug.RenoirCache) {
```suggestion
  setRenoirCacheState(stateToSet: Protocol.CohtmlDebug.RenoirCache): void {
```

2023-04-11 12:07 UTC, alien1976 commented on front_end/entrypoints/inspector_main/CohtmlPanel.ts
> +      entryInput.setAttribute('type', 'text');
Why the input type is not a number?

2023-04-11 12:07 UTC, alien1976 commented on third_party/blink/public/devtools_protocol/browser_protocol.json
> +                            "$ref": "strign"
```suggestion
                            "$ref": "string"
```

2023-04-19 15:36 UTC, palikar commented on front_end/entrypoints/inspector_main/CohtmlPanel.ts
> +      entryInput.setAttribute('type', 'text');
sure, fixed

2023-04-19 15:36 UTC, palikar commented on front_end/core/sdk/CohtmlDebugModel.ts
> +  setRenoirCacheState(stateToSet: Protocol.CohtmlDebug.RenoirCache) {
fixed

2023-04-19 15:40 UTC, palikar commented on third_party/blink/public/devtools_protocol/browser_protocol.json
> +                            "$ref": "strign"
fixed

2023-04-21 14:30 UTC, omalinov approved these changes

2023-04-21 14:33 UTC, alien1976 approved these changes

2023-04-24 11:18 UTC, merged